import aiohttp
import asyncio
import json

URL = "https://www.autotrader.co.uk/at-graphql?opname=SearchFormFacetsQuery"

HEADERS = {
    "Accept": "*/*",
    "Accept-Language": "en-GB,en;q=0.9",
    "Content-Type": "application/json",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.5 Safari/605.1.15",
    "x-sauron-app-name": "sauron-research-hub-app",
    "x-sauron-app-version": "bad72303bf"
}

def build_payload(make=None):
    advert_query = {
        "postcode": "sw1a1aa",
        "homeDeliveryAdverts": "include",
        "advertClassification": ["standard"],
        "advertisingLocations": ["at_cars"],
        "maxYear": "2026"
    }
    
    if make:
        advert_query["make"] = [make]

    return [{
        "operationName": "SearchFormFacetsQuery",
        "variables": {
            "advertQuery": advert_query,
            "facets": ["make", "model"] if not make else ["model"]
        },
        "query": "query SearchFormFacetsQuery($advertQuery: AdvertQuery!, $facets: [SearchFacetName]) {\n  search {\n    adverts(advertQuery: $advertQuery) {\n      facets(facets: $facets) {\n        name\n        values {\n          name\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}"
    }]

async def fetch_models_for_make(session, make, semaphore):
    async with semaphore:
        print(f"Fetching models for {make}...")
        try:
            async with session.post(URL, json=build_payload(make)) as response:
                if response.status != 200:
                    print(f"Failed to fetch models for {make} (Status: {response.status})")
                    return make, []
                
                data = await response.json()
                facets = data[0]['data']['search']['adverts']['facets']
                
                for facet in facets:
                    if facet['name'] == 'model':
                        models = [v['name'] for v in facet['values']]
                        return make, models
                        
        except Exception as e:
            print(f"Error fetching {make}: {e}")
            
        return make, []

async def main():
    print("Fetching all available makes...")
    
    async with aiohttp.ClientSession(headers=HEADERS) as session:
        # Step 1: Fetch all makes
        async with session.post(URL, json=build_payload()) as response:
            if response.status != 200:
                print(f"Failed to fetch makes. Status {response.status}")
                return
            
            data = await response.json()
            facets = data[0]['data']['search']['adverts']['facets']
            makes = []
            for facet in facets:
                if facet['name'] == 'make':
                    makes = [v['name'] for v in facet['values']]
                    break
                    
        print(f"Found {len(makes)} makes. Now fetching models for each...")
        
        # Step 2: Fetch models for each make concurrently (with a limit)
        semaphore = asyncio.Semaphore(10) # Limit to 10 concurrent requests to avoid rate limits
        tasks = [fetch_models_for_make(session, make, semaphore) for make in makes]
        
        results = await asyncio.gather(*tasks)
        
        # Step 3: Build dictionary and write to python file
        car_data = {make: models for make, models in results if models}
        
        print(f"Finished! Found models for {len(car_data)} makes.")
        print("Writing to autotrader_data.py...")
        
        with open("autotrader_data.py", "w") as f:
            f.write("# This file is auto-generated by get_makes_models.py\n\n")
            f.write("CAR_DATA = {\n")
            for make, models in sorted(car_data.items()):
                f.write(f'    "{make}": {json.dumps(models)},\n')
            f.write("}\n")
            
        print("Done! You can now `from autotrader_data import CAR_DATA` in your bot.")

if __name__ == "__main__":
    asyncio.run(main())
